import type { InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const ROOT_LEVEL = -1;

type Employee = {
  name: string;
  id: number;
  title: string;
  manager_id?: number;
};

interface Props {
  employeeOrgMap: Record<number, Employee[]>;
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(
    `https://gist.githubusercontent.com/chancock09/6d2a5a4436dcd488b8287f3e3e4fc73d/raw/fa47d64c6d5fc860fabd3033a1a4e3c59336324e/employees.json`
  );
  const employeeData: Employee[] = await res.json();

  const employeeOrgMap = employeeData.reduce((prev, curr) => {
    if (!curr.manager_id) {
      curr.manager_id = ROOT_LEVEL;
    }
    if (!prev[curr.manager_id]) {
      prev[curr.manager_id] = [];
    }
    prev[curr.manager_id].push(curr);

    return prev;
  }, {} as Record<number, Employee[]>);

  // Pass data to the page via props
  return { props: { employeeOrgMap } };
}

const Home: NextPage<Props> = ({ employeeOrgMap }) => {
  const renderOrgChart = (level: number) => {
    const employees = employeeOrgMap[level];

    if (!employees) {
      return;
    }

    return employees
      .sort((a, b) => {
        const aLastName = a.name.split(" ")[1];
        const bLastName = b.name.split(" ")[1];
        if (!aLastName) {
          return 1;
        }

        if (!bLastName) {
          return -1;
        }
        return aLastName.localeCompare(bLastName);
      })
      .map((employee) => {
        return (
          <ol>
            <ol className={styles.employeeRow}>
              {employee.title}: {employee.name}
            </ol>
            {renderOrgChart(employee.id)}
          </ol>
        );
      });
  };
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.wanderjaunt.com/">WanderJaunt</a>
        </h1>
        <h2>Employees</h2>

        {renderOrgChart(ROOT_LEVEL)}
      </main>
    </div>
  );
};

export default Home;
